### ISSUE TITLE
Add PM calculation to module aop

### ISSUE THREAD

**Issue by amdasilva** [GEOS-ESM/GMAOpyobs#48]
Module aop.py is meant as a calculator of Aerosol Optical Properties by convolving aerosol mixing ratios found in the are_Nv collection with the optics LUTs. The calculation of PM, while not strictly an "optical property" makes use of the same aer_Nv collection and the same optics LUTs, thus it makes sense to introduce a *getPM* method to aop.py.

In addition, in function CLI_aop() which parses the command line and serves as an entry point application, please extend option "--aop" by handling the option "--aop pm" for creating files with PM variables.  Notice that you have to special handle config.aop =='pm' near line 518. Also, notice that you may need to create additional options to costuming the way PM is calculated.  Some considerations:

* you may want to always create files with PM1, PM2.5 and PM10. Alternatively, you may create an option (similar to wavelengths) where you specify the PM sizes of interest, defaulting to 1, 2.5 & 10
* you may want to create an --rh option which can override the RH found on file. This could be used for all the AOPs, not only PM. 

Please talk to me about these UI design options.

**Comment by patricia-nasa** [comment]
Resolved by PR #49
